# Generated by Django 5.2.14 on 2026-05-27 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY')], max_length=50)),
                ('file_type', models.CharField(choices=[('FUEL', 'FUEL'), ('PROCUREMENT', 'PROCUREMENT'), ('ELECTRICITY', 'ELECTRICITY')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MANDT', models.CharField(blank=True, max_length=50, null=True)),
                ('EBELN', models.CharField(blank=True, max_length=50, null=True)),
                ('EBELP', models.CharField(blank=True, max_length=50, null=True)),
                ('AEDAT', models.CharField(blank=True, max_length=50, null=True)),
                ('KNTTP', models.CharField(blank=True, max_length=50, null=True)),
                ('ANLN1', models.CharField(blank=True, max_length=50, null=True)),
                ('TXZ01', models.TextField(blank=True, null=True)),
                ('MENGE', models.FloatField(blank=True, null=True)),
                ('MEINS', models.CharField(blank=True, max_length=50, null=True)),
                ('NETPR', models.FloatField(blank=True, null=True)),
                ('WAERS', models.CharField(blank=True, max_length=20, null=True)),
                ('WERKS', models.CharField(blank=True, max_length=50, null=True)),
                ('LIFNR', models.CharField(blank=True, max_length=50, null=True)),
                ('NAME1', models.CharField(blank=True, max_length=255, null=True)),
                ('MATKL', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('WARNING', 'WARNING'), ('SUSPICIOUS', 'SUSPICIOUS'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='ingestion.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MANDT', models.CharField(blank=True, max_length=50, null=True)),
                ('EBELN', models.CharField(blank=True, max_length=50, null=True)),
                ('EBELP', models.CharField(blank=True, max_length=50, null=True)),
                ('AEDAT', models.CharField(blank=True, max_length=50, null=True)),
                ('MATNR', models.CharField(blank=True, max_length=100, null=True)),
                ('TXZ01', models.TextField(blank=True, null=True)),
                ('MENGE', models.FloatField(blank=True, null=True)),
                ('MEINS', models.CharField(blank=True, max_length=50, null=True)),
                ('NETPR', models.FloatField(blank=True, null=True)),
                ('PEINH', models.CharField(blank=True, max_length=50, null=True)),
                ('WAERS', models.CharField(blank=True, max_length=20, null=True)),
                ('WERKS', models.CharField(blank=True, max_length=50, null=True)),
                ('LGORT', models.CharField(blank=True, max_length=50, null=True)),
                ('LIFNR', models.CharField(blank=True, max_length=50, null=True)),
                ('NAME1', models.CharField(blank=True, max_length=255, null=True)),
                ('MATKL', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('WARNING', 'WARNING'), ('SUSPICIOUS', 'SUSPICIOUS'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='ingestion.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Account_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Facility_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Meter_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Billing_Start', models.DateField(blank=True, null=True)),
                ('Billing_End', models.DateField(blank=True, null=True)),
                ('Previous_Reading', models.FloatField(blank=True, null=True)),
                ('Current_Reading', models.FloatField(blank=True, null=True)),
                ('Multiplier', models.FloatField(blank=True, null=True)),
                ('kWh_Usage', models.FloatField(blank=True, null=True)),
                ('Tariff_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Rate_Per_kWh', models.FloatField(blank=True, null=True)),
                ('Fixed_Charge', models.FloatField(blank=True, null=True)),
                ('Tax_Amount', models.FloatField(blank=True, null=True)),
                ('Total_Amount', models.FloatField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=20, null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('WARNING', 'WARNING'), ('SUSPICIOUS', 'SUSPICIOUS'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='ingestion.uploadedfile')),
            ],
        ),
    ]
