# Generated by Django 5.2.14 on 2026-05-27 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityESGRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=255)),
                ('meter_id', models.CharField(max_length=255)),
                ('electricity_usage', models.FloatField()),
                ('normalized_unit', models.CharField(default='kWh', max_length=50)),
                ('register_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff_code', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('billing_end', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(default='Scope 2', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.electricityrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FuelESGRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('scope', models.CharField(default='Scope 1', max_length=50)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.fuelrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementESGRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_category', models.CharField(max_length=255)),
                ('material_description', models.TextField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=255)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(default='Scope 3', max_length=50)),
                ('spend_amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.procurementrecord')),
            ],
        ),
    ]
