# Generated by Django 5.2.14 on 2026-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_electricityesgrecord_fuelesgrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelesgrecord',
            name='normalized_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
