# Generated by Django 5.2.14 on 2026-05-27 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ingestion', '0003_fuelesgrecord_normalized_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('severity', models.CharField(choices=[('FAILED', 'FAILED'), ('WARNING', 'WARNING'), ('SUSPICIOUS', 'SUSPICIOUS')], max_length=20)),
                ('issue_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
