# Generated by Django 5.2.14 on 2026-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_validationissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementesgrecord',
            name='normalized_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementesgrecord',
            name='normalized_unit',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
