# Generated by Django 5.2.14 on 2026-05-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_procurementesgrecord_normalized_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementesgrecord',
            name='normalized_unit',
        ),
    ]
