# Generated by Django 5.2.14 on 2026-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_remove_procurementesgrecord_normalized_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityesgrecord',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='current_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='previous_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='rate_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
