# Generated by Django 5.2.14 on 2026-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_electricityesgrecord_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('electricity', 'Electricity'), ('procurement', 'Procurement')], max_length=50)),
                ('factor_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='electricityesgrecord',
            name='calculated_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelesgrecord',
            name='calculated_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementesgrecord',
            name='calculated_emission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
