# Generated by Django 5.2.14 on 2026-05-28 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0008_emissionfactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=255)),
                ('trip_id', models.CharField(max_length=255)),
                ('booking_status', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('imported_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelESGRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_type', models.CharField(default='Flight', max_length=100)),
                ('scope', models.CharField(default='Scope 3', max_length=50)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('calculated_emission', models.FloatField(blank=True, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.travelbooking')),
            ],
        ),
    ]
